 node {
     parameters {
         string(name : 'BUILD_NM', defaultValue : '0', description : '')
     }

     stage('✨ Clone Repo') {
         checkout scm
     }

     stage('🐳 Dk Build') {

        withCredentials([gitUsernamePassword(credentialsId: 'my-credentials-id', gitToolName: 'git-tool')]) {
          sh "sed -i 's/image:.*/image: ${params.BUILD_NM}/g' values.yaml"
          sh "git config --global user.email 'ckrbqja@gmail.com'"
          sh "git config --global user.name 'ckrbqja'"
          sh "git add ."
          sh "git commit -m '[Argo] Docker image tag: ${params.BUILD_NM}'"
          sh "git push --force origin master"
        }
     }


     stage('🚀 Push Image') {
         docker.withRegistry( 'https://' + imageName , credentials) {
             applicationNm = sh(script:"docker ps | grep netjs | awk '\$0=\$12'", returnStdout: true).trim()

//              TARGET_COLOR = applicationNm == "netjs-blue" ? "green" : "blue"
//              TARGET_ICON = applicationNm == "netjs-blue" ? "🔵" : "🟢"
//
//              echo "> $TARGET_ICON $TARGET_COLOR 빌드"
//
//              app.push(TARGET_COLOR)
             app.push('latest')
         }
     }

 }
