 node {
     parameters {
         string(name : 'BUILD_NM', defaultValue : '0', description : '')
         string(name : 'AWS_URL', defaultValue : '0', description : '')
         string(name : 'REPO_NM', defaultValue : '0', description : '')
     }

     stage('✨ Clone Repo') {
         checkout scm
     }

     stage('🐳 Dk Build') {

        withCredentials([gitUsernamePassword(credentialsId: 'my-credentials-id', gitToolName: 'git-tool')]) {
          sh "sed -i 's@image:.*@image: ${params.AWS_URL}/${params.REPO_NM}:${params.BUILD_NM}@g' values.yaml"
          sh "git config --global user.email 'ckrbqja@gmail.com'"
          sh "git config --global user.name 'ckrbqja'"
          sh "git add ."
          sh "git commit -m '[Argo] Docker image tag: ${params.BUILD_NM}'"
          sh "git push -f origin aa"
        }
     }

 }
