apiVersion: apps/v1
kind: Deployment
metadata:
  name: ff
spec:
  replicas: 5
  selector:
    matchLabels:
      name: aa
  template:
    metadata:
      labels:
        name: aa
      name: bb
    spec:
      containers:
        - name: aa
          image: 967699999360.dkr.ecr.ap-northeast-2.amazonaws.com/result:28
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry
