apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 2
  selector:
    matchLabels:
        name: result-api
  template:
    metadata:
      name: result-api
      namespace: result-api
      labels:
        name: result-api
    spec:
      containers:
        - name: aa
          image: '967699999360.dkr.ecr.ap-northeast-2.amazonaws.com/result:28'
      imagePullSecrets:
        - name: ap-northeast-2-ecr-registry
                                                               
      #containers:
      #  - name: result-api-pod
      #    image: {{ .Values.image }}:{{ .Values.version }}
      #imagePullSecrets:
      #  - name: ap-northeast-2-ecr-registry

