apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}

spec:
  replicas: 2
  selector:
    matchLabels:
        name: result-api
  template:
    metadata:
      name: result-api
      namespace: result-api
      labels:
        name: result-api
    spec:
      containers:
        - name: result-api-pod
          image: {{ .Values.image }}:{{ .Values.port }}

