apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    name: result-api
  type: NodePort
  ports:
    - port: 80
      targetPort: 8993
      protocol: TCP
